[tool.poetry]
name = "lia"
version = "1.0.0"
description = "LIA"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "1.1.5"
numpy = "1.20.1"
fsspec = "0.8.7"
mlconjug3 = "^3.7.20"
Levenshtein = "^0.15.0"
spacy = "^3.1.3"
st-annotated-text = "^2.0.0"
pysinonimos = "^0.1.1"
streamlit = "^0.89.0"
watchdog = "^2.1.5"
matplotlib = "^3.4.3"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
