name: Secrets_Production
on:
  workflow_dispatch:

jobs:
  production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action Repo
        uses: actions/checkout@v2
        with:
          repository: loft-br/actions
          ref: main
          token: ${{ secrets.GIT_HUB_TOKEN }} # stored in GitHub secrets
          path: .github/actions/loft
      - name: Create Secret in K8S
        uses: ./.github/actions/loft/create_secret
        env:
          APP_ACCESS_KEY: ${{ secrets.GONAN_AUTH }}
        with:
          environment: production
          artifact: lia
          map: |
            AWS_APP_ACCESS_KEY_ID=${{ secrets.AWS_APP_ACCESS_KEY_ID }}
            AWS_APP_SECRET_ACCESS_KEY=${{ secrets.AWS_APP_SECRET_ACCESS_KEY }}